// GENERATED by tools/fetch-brand.mjs — do not edit by hand.
// Source: https://raw.githubusercontent.com/anomalyco/opencode/dev/packages/tui/src/logo.ts (packages/tui/src/logo.ts, export const logo)

/** Left box ("open") — 4 rows x 19 cols of block-pixel ASCII. */
export const WORDMARK_LEFT: string[] = [
  "                   ",
  "█▀▀█ █▀▀█ █▀▀█ █▀▀▄",
  "█__█ █__█ █^^^ █__█",
  "▀▀▀▀ █▀▀▀ ▀▀▀▀ ▀~~▀"
];

/** Right box ("code") — 4 rows x 19 cols of block-pixel ASCII. */
export const WORDMARK_RIGHT: string[] = [
  "             ▄     ",
  "█▀▀▀ █▀▀█ █▀▀█ █▀▀█",
  "█___ █__█ █__█ █^^^",
  "▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀"
];

/** Marks the TUI renderer understands: _ ^ ~ , */
export const WORDMARK_MARKS = '_^~,';
