// Regenerates src/assets/wordmarkData.ts from the official opencode TUI source.
// Hand-transcribing block-pixel art is a corruption risk, so we parse the real
// file instead. Run: node tools/fetch-brand.mjs

import { writeFileSync } from 'node:fs';

const URL_LOGO_TS = 'https://raw.githubusercontent.com/anomalyco/opencode/dev/packages/tui/src/logo.ts';
const OUT = new URL('../src/assets/wordmarkData.ts', import.meta.url);

const res = await fetch(URL_LOGO_TS);
if (!res.ok) {
  console.error(`fetch failed: ${res.status} ${URL_LOGO_TS}`);
  process.exit(1);
}
const src = await res.text();

const grab = (key) => {
  const m = src.match(new RegExp(`${key}:\\s*\\[([^\\]]+)\\]`));
  if (!m) throw new Error(`could not find ${key} in logo.ts`);
  return m[1]
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length && s !== '""')
    .map((s) => JSON.parse(s));
};

const left = grab('left');
const right = grab('right');

if (left.length !== 4 || right.length !== 4) {
  throw new Error(`expected 4 rows per box, got left=${left.length} right=${right.length}`);
}
for (const [i, row] of [...left, ...right].entries()) {
  if ([...row].length !== 19) {
    throw new Error(`row ${i} is not 19 columns (got ${[...row].length}): ${JSON.stringify(row)}`);
  }
}

const ts = `// GENERATED by tools/fetch-brand.mjs — do not edit by hand.
// Source: ${URL_LOGO_TS} (packages/tui/src/logo.ts, export const logo)

/** Left box ("open") — 4 rows x 19 cols of block-pixel ASCII. */
export const WORDMARK_LEFT: string[] = ${JSON.stringify(left, null, 2).replace(/\n/g, '\n')};

/** Right box ("code") — 4 rows x 19 cols of block-pixel ASCII. */
export const WORDMARK_RIGHT: string[] = ${JSON.stringify(right, null, 2)};

/** Marks the TUI renderer understands: _ ^ ~ , */
export const WORDMARK_MARKS = '_^~,';
`;

writeFileSync(OUT, ts, 'utf8');
console.log('wrote', OUT.pathname);
console.log('left rows:');
for (const r of left) console.log('  |' + r + '|', [...r].length, 'cols');
console.log('right rows:');
for (const r of right) console.log('  |' + r + '|', [...r].length, 'cols');
